let menu = '<div class="container">'
+ '<a class="navbar-brand" href="index.html">CAM</a>'
+ '<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">'
+  'Menu' 
+  '<i class="fas fa-bars"></i>'
+ '</button>'
+ '<div class="collapse navbar-collapse" id="navbarResponsive">'
+  '<ul class="navbar-nav ml-auto">'
+    '<li class="nav-item">'
+      '<a class="nav-link" href="../basic/index.html">Inicio</a>'
+    '</li>'
+    '<li class="nav-item">'
+      '<a class="nav-link" href="../basic/about.html">Sobre</a>'
+    '</li>'
+    '<li class="nav-item dropdown">'
+      '<a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true">Mensagens</a>'
+           '<div class="dropdown-menu">'
+               '<a class="dropdown-item" href="../basic/post.html">Maio</a>'
+               '<div class="dropdown-divider"></div>'
+               '<a class="dropdown-item" href="../2020/maio.html">Maio</a>'
+               '<div class="dropdown-divider"></div>'
+               '<a class="dropdown-item" href="../2020/abril.html">Abril</a>'
+               '<div class="dropdown-divider"></div>'
+               '<a class="dropdown-item" href="../2020/marco.html">Março</a>'
+               '<div class="dropdown-divider"></div>'
+               '<a class="dropdown-item" href="../2020/fevereiro.html">Fevereiro</a>'
+               '<div class="dropdown-divider"></div>'
+               '<a class="dropdown-item" href="../2020/janeiro.html">Janeiro</a>'
+           '</div>'
+    '</li>'
+    '<li class="nav-item">'
+      '<a class="nav-link" href="../basic/contact.html">Contato</a>'
+    '</li>'
+  '</ul>'
+'</div>'
+'</div>'